import { config } from '../shared/config';
import { assertOk } from '../shared/http-util';
import type { IntentResult } from '../shared/types';

export interface LLMProvider {
  name: string;
  parseIntent(text: string, customSystemPrompt?: string): Promise<IntentResult>;
  generateCompletion(systemPrompt: string, userPrompt: string): Promise<string>;
}

interface ChatMessage {
  role: string;
  content: string;
}

export function getSystemPrompt(customContext?: string): string {
  const globalContext = customContext || 'pixi is an intelligent voice-first Windows desktop assistant.';
  return `You are the core intelligence and intent parser for a Windows voice assistant named pixi.
Your job is to understand user requests, follow global behavioral guidelines and long-term memories, and return a JSON object matching one of the allowed intents.

Global Assistant Behavior, Persona & Memory Context:
---
${globalContext}
---

Allowed intents and required params:
- chat.respond: { message: string } (use this for any general conversation, question, or general query)
- reminder.create: { text: string, due: ISO-8601 datetime string }
- reminder.list: {}
- reminder.complete: { id?: number, text?: string }
- todo.create: { text: string }
- todo.list: {}
- todo.complete: { id?: number, text?: string }
- unknown: {} (use only if the request is truly unprocessable nonsense)

Current date and time: ${new Date().toISOString()}

Important rules:
- Adhere strictly to the global persona and behavioral rules above in all sessions.
- In chat.respond, keep messages concise, direct, helpful, and natural for text-to-speech reading.
- If the user asks for something outside these capabilities, do NOT invent an intent. Use "chat.respond" and concisely explain what capabilities are available.
- Always respond in valid JSON only. No explanations before or after the JSON.
- For relative times like "tomorrow at 5pm", output a full ISO-8601 datetime.

Example output for "remind me to call mom tomorrow at 10am":
{"intent":"reminder.create","params":{"text":"call mom","due":"2026-07-31T10:00:00"}}`;
}

function parseContentToIntent(content: unknown): IntentResult {
  let parsed: any;
  if (typeof content === 'object' && content !== null) {
    parsed = content;
  } else {
    const str = typeof content === 'string' ? content : JSON.stringify(content || {});
    const cleaned = str.replace(/```json|```/g, '').trim();
    try {
      parsed = JSON.parse(cleaned);
    } catch {
      return {
        intent: 'chat.respond',
        params: { message: cleaned },
      };
    }
  }

  if (!parsed || typeof parsed !== 'object') {
    return { intent: 'unknown', params: {} as any };
  }

  const intent = parsed.intent || 'chat.respond';
  const params = parsed.params && typeof parsed.params === 'object' ? { ...parsed.params } : {};

  // Normalize top-level fields often generated by local LLMs (Ollama / Llama 3.2):
  if (parsed.message && !params.message) params.message = parsed.message;
  if (parsed.text && !params.text) params.text = parsed.text;
  if (parsed.due && !params.due) params.due = parsed.due;
  if (parsed.id !== undefined && params.id === undefined) params.id = parsed.id;
  if (parsed.response && !params.message) params.message = parsed.response;

  return { intent, params } as IntentResult;
}

export class OpenAICompatibleLLM implements LLMProvider {
  public name: string;
  private baseUrl: string;
  private apiKey: string;
  private model: string;

  constructor(baseUrl: string, apiKey: string, model: string, name = 'openai') {
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
    this.model = model;
    this.name = name;
  }

  private authHeaders() {
    return {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${this.apiKey}`,
    };
  }

  private async chat(
    messages: ChatMessage[],
    temperature: number,
    label: string,
    extra: Record<string, unknown> = {},
  ): Promise<any> {
    if (!this.apiKey) throw new Error(`${this.name} API key is missing.`);

    const res = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: this.authHeaders(),
      body: JSON.stringify({ model: this.model, messages, temperature, ...extra }),
    });

    await assertOk(res, `${this.name} ${label}`);
    return res.json();
  }

  async parseIntent(text: string, customSystemPrompt?: string): Promise<IntentResult> {
    const sysPrompt = getSystemPrompt(customSystemPrompt);
    const extra = this.name === 'openai' ? { response_format: { type: 'json_object' } } : {};
    const data = await this.chat(
      [
        { role: 'system', content: sysPrompt },
        { role: 'user', content: text },
      ],
      0.2,
      'LLM',
      extra,
    );

    const content = data.choices?.[0]?.message?.content;
    return parseContentToIntent(content);
  }

  async generateCompletion(systemPrompt: string, userPrompt: string): Promise<string> {
    const data = await this.chat(
      [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      0.3,
      'completion',
    );

    return data.choices?.[0]?.message?.content || '';
  }
}

export class GeminiLLM implements LLMProvider {
  public name = 'gemini';
  private apiKey: string;
  private model: string;

  constructor(apiKey: string, model: string) {
    this.apiKey = apiKey;
    this.model = model || 'gemini-1.5-flash';
  }

  private get url() {
    return `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;
  }

  private async generateContent(
    systemPrompt: string,
    userPrompt: string,
    temperature: number,
    label: string,
  ): Promise<string> {
    if (!this.apiKey) throw new Error('Gemini API key is missing.');

    const res = await fetch(this.url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          { role: 'user', parts: [{ text: systemPrompt }] },
          { role: 'user', parts: [{ text: userPrompt }] },
        ],
        generationConfig: { temperature },
      }),
    });

    await assertOk(res, `Gemini ${label}`);

    const data = await res.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
  }

  async parseIntent(text: string, customSystemPrompt?: string): Promise<IntentResult> {
    const sysPrompt = getSystemPrompt(customSystemPrompt);
    const content = await this.generateContent(sysPrompt, text, 0.2, 'LLM');
    return parseContentToIntent(content);
  }

  async generateCompletion(systemPrompt: string, userPrompt: string): Promise<string> {
    return this.generateContent(systemPrompt, userPrompt, 0.3, 'completion');
  }
}

export class OllamaLLM implements LLMProvider {
  public name = 'ollama';
  private baseUrl: string;
  private model: string;

  constructor(baseUrl: string, model: string) {
    this.baseUrl = baseUrl;
    this.model = model || 'llama3.2:3b';
  }

  private async generate(
    prompt: string,
    label: string,
    extra: Record<string, unknown> = {},
  ): Promise<string> {
    const res = await fetch(`${this.baseUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: this.model, prompt, stream: false, ...extra }),
    });

    await assertOk(res, `Ollama ${label}`);

    const data = await res.json();
    return data.response || '';
  }

  async parseIntent(text: string, customSystemPrompt?: string): Promise<IntentResult> {
    const sysPrompt = getSystemPrompt(customSystemPrompt);
    const content = await this.generate(`${sysPrompt}\n\nUser: ${text}\n\nIntent JSON:`, 'LLM', { format: 'json' });
    return parseContentToIntent(content);
  }

  async generateCompletion(systemPrompt: string, userPrompt: string): Promise<string> {
    return this.generate(`${systemPrompt}\n\n${userPrompt}`, 'completion');
  }
}

export function createPrimaryLLMProvider(): LLMProvider | null {
  const provider = config.llm.provider;

  switch (provider) {
    case 'opencode':
      if (config.llm.openCodeKey) {
        const model = process.env.OPENCODE_MODEL || (config.llm.model && config.llm.model !== 'gpt-4o-mini' && config.llm.model !== 'gemini-1.5-flash' ? config.llm.model : 'space-bunny-free');
        return new OpenAICompatibleLLM('https://opencode.ai/zen/v1', config.llm.openCodeKey, model, 'opencode');
      }
      console.warn('[LLM] Provider forced to opencode but OPENCODE_API_KEY missing.');
      return null;
    case 'gemini':
      if (config.llm.geminiKey) return new GeminiLLM(config.llm.geminiKey, config.llm.model);
      console.warn('[LLM] Provider forced to gemini but GEMINI_API_KEY missing.');
      return null;
    case 'openai':
      if (config.llm.openAiKey) return new OpenAICompatibleLLM('https://api.openai.com/v1', config.llm.openAiKey, config.llm.model, 'openai');
      console.warn('[LLM] Provider forced to openai but OPENAI_API_KEY missing.');
      return null;
    case 'ollama':
    default:
      return null;
  }
}